### ISSUE TITLE
SBT error while fetching deps

### ISSUE THREAD

**Issue by max-leuthaeuser** [mohiva/play-silhouette-seed#20]
Sadly some dependencies are missing at the moment.

*SBT (0.13.7)*

```
... more ...
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/atlassian/jwt/jwt-api/1.2.1/jwt-api-1.2.1.jar
[warn] ==== Typesafe Releases Repository: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/atlassian/jwt/jwt-api/1.2.1/jwt-api-1.2.1.jar
[warn] ==== Sonatype Snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/com/atlassian/jwt/jwt-api/1.2.1/jwt-api-1.2.1.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.atlassian.jwt#jwt-core;1.2.1!jwt-core.jar
[warn] 	:: com.atlassian.jwt#jwt-api;1.2.1!jwt-api.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: download failed: com.atlassian.jwt#jwt-core;1.2.1!jwt-core.jar
[error] download failed: com.atlassian.jwt#jwt-api;1.2.1!jwt-api.jar
```

Some way to fix this?

**Comment by akkie** [comment]
Please can you try to use the activator command. I had the same issue with sbt directly a short while ago. It seems the problem is that the jwt-lib is hosted on [bintray.com](https://bintray.com/bintray/jcenter/com.atlassian.jwt:jwt-api) and then mirrored to the typesafe.com repository. It seems that the typesafe repository uses a redirect which sbt doesn't understand.

If you try to download the file directly from the typesafe URL then you can download it.
https://repo.typesafe.com/typesafe/releases/com/atlassian/jwt/jwt-api/1.2.1/jwt-api-1.2.1.jar

Maybe I should use a bintray resolver for this lib.

Let me know if it works.

**Comment by max-leuthaeuser** [comment]
I manually downloaded it and put it in the local .ivy cache. Works.
Not a valid solution for my production code though :)

**Comment by akkie** [comment]
Does it work with the `activator` command from Play?

**Comment by max-leuthaeuser** [comment]
I am not using it. I am only running SBT.

**Comment by akkie** [comment]
OK, thanks. I've opened a new issue on Silhouette directly.

**Comment by akkie** [comment]
The issue is now fixed.

**Comment by ndeverge** [comment]
I also had the same issue with `2.0-RC1`.
I had to add the Atlassian resolver to my `build.sbt`: 

```
resolvers += "Atlassian Releases" at "https://maven.atlassian.com/public/"
```

**Comment by akkie** [comment]
@ndeverge This is an issue in [sbt](https://github.com/sbt/sbt/issues/1820). You have to be careful that the resolver comes before the Typesafe resolver. Therefore I add it to the [beginning](https://github.com/mohiva/play-silhouette-seed/blob/master/build.sbt#L11).

**Comment by ndeverge** [comment]
@akkie My issue was not where to add the resolver, but to simply add it (and maybe this comment will help further users).

And for information, I added it at the end of my `build.sbt` file, and it works, with this syntax:
```
resolvers += "Atlassian Releases" at "https://maven.atlassian.com/public/"
```

**Comment by akkie** [comment]
Sure, but it can be error-prone if the resolver will be blindly added to the end of the resolver list. The problem is that if the Typesafe resolver was added before the Atlassian resolver then sbt tries to download the package from the Typesafe repository. Because of the fact that the package can be found in the Typesafe repository, sbt tries to download it. But then sbt stops with an error that it cannot handle the redirect. It wasn't my intention to blame you with this comment. It should only be an additional note for your and the other users.

**Comment by ndeverge** [comment]
Ok, thanks for the explanation.

An keep up the good work, Silhouette is awesome :clap:
