### ISSUE TITLE
Demo link is down in 1.0 version

### ISSUE THREAD

**Issue by mkbehbehani** [mohiva/play-silhouette-seed#25]
http://play-silhouette-seed.mohiva.cloudbees.net/ gives a 404, could you upload the 1.0 to Heroku similarly to the 2.0 version?

**Comment by akkie** [comment]
Thanks for your feedback and your interest in Silhouette. I'm sorry to say that I'll not put any effort into version 1.0 because the release of the stable 2.0 is almost here. There is also no difference, in visible functionality, between the 1.0 and 2.0 version of the seed template.

If you start a new project please use version 2.0. It has more features and a better documentation. I plan to release version 2.0 in the next two weeks.

**Comment by mkbehbehani** [comment]
Sounds good, thank you!
